### ISSUE TITLE
401 auth error when getting target ID

### ISSUE THREAD

**Issue by jrdeck** [TheGrandWazoo/freenas-proxmox#6]
_Environment:_
FreeNAS build FreeNAS-11.1-U5
Proxmox Virtual Environment 5.2-1

_ZFS over iSCSI definition in Proxmox:_
ID: zfs-over-scsi0
Portal: <<IP of FreeNAS box>>
Pool: pool0
Target: iqn.2005-10.org.freenas.ctl:target2
FreeNAS user: root
FreeNAS password: <<root pw>>

_FreeNAS config:_
Portal Group ID: 1
Target Name: target2
Extent Name: extent0
Extent Type: file
Extent Path: /mnt/fast0/extent0
Target/Extent: links target2 and extent0

_Issue:_
When creating a VM, the disk image appears in the Proxmox backend. However, the *create* task creates with:

`TASK ERROR: create failed - error with cfs lock 'storage-zfs-over-scsi0': Unable to find the target id for iqn.2005-10.org.freenas.ctl:target2 at /usr/share/perl5/PVE/Storage/LunCmd/FreeNAS.pm line 124.
`

Relevant entry on the Proxmox side in `/var/log/syslog/`:

> Jul  9 10:04:31 prox01test pvedaemon[94112]: <root@pam> starting task UPID:prox01test:00016FCB:016C7286:5B42A68F:qmcreate:112:root@pam:
> Jul  9 10:04:31 prox01test pvedaemon[94155]: FreeNAS::lun_command : create_lu(/dev/zvol/fast0/vm-112-disk-1)
> Jul  9 10:04:32 prox01test pvedaemon[94155]: [ERROR]FreeNAS::API::get_globalconfig : Response code: 401
> Jul  9 10:04:32 prox01test pvedaemon[94155]: [ERROR]FreeNAS::API::get_globalconfig : Response content:
> Jul  9 10:04:32 prox01test pvedaemon[94155]: [ERROR]FreeNAS::API::get_target : Response code: 401
> Jul  9 10:04:32 prox01test pvedaemon[94155]: [ERROR]FreeNAS::API::get_target : Response content:
> Jul  9 10:04:32 prox01test pvedaemon[94155]: [ERROR]FreeNAS::API::get_target_to_extent : Response code: 401
> Jul  9 10:04:32 prox01test pvedaemon[94155]: [ERROR]FreeNAS::API::get_target_to_extent : Response content:
> Jul  9 10:04:32 prox01test pvedaemon[94155]: FreeNAS::API::freenas_get_first_available_lunid : return 0
> Jul  9 10:04:32 prox01test pvedaemon[94155]: [ERROR]FreeNAS::API::get_target : Response code: 401
> Jul  9 10:04:32 prox01test pvedaemon[94155]: [ERROR]FreeNAS::API::get_target : Response content:
> Jul  9 10:04:32 prox01test pvedaemon[94155]: [ERROR]FreeNAS::API::get_globalconfig : Response code: 401
> Jul  9 10:04:32 prox01test pvedaemon[94155]: [ERROR]FreeNAS::API::get_globalconfig : Response content:
> Jul  9 10:04:32 prox01test pvedaemon[94155]: [ERROR]FreeNAS::API::get_target : Response code: 401
> Jul  9 10:04:32 prox01test pvedaemon[94155]: [ERROR]FreeNAS::API::get_target : Response content:
> Jul  9 10:04:32 prox01test pvedaemon[94155]: FreeNAS::API::freenas_list_lu : sucessfull
> Jul  9 10:04:32 prox01test pvedaemon[94155]: FreeNAS::list_lu(/dev/zvol/fast0/vm-112-disk-1):name : lun not found
> Jul  9 10:04:32 prox01test pvedaemon[94155]: [ERROR]FreeNAS::API::get_globalconfig : Response code: 401
> Jul  9 10:04:32 prox01test pvedaemon[94155]: [ERROR]FreeNAS::API::get_globalconfig : Response content:
> Jul  9 10:04:32 prox01test pvedaemon[94155]: [ERROR]FreeNAS::API::get_target : Response code: 401
> Jul  9 10:04:32 prox01test pvedaemon[94155]: [ERROR]FreeNAS::API::get_target : Response content:
> Jul  9 10:04:32 prox01test pvedaemon[94155]: VM 112 creating disks failed
> Jul  9 10:04:32 prox01test pvedaemon[94155]: create failed - error with cfs lock 'storage-zfs-over-scsi0': Unable to find the target id for iqn.2005-10.org.freenas.ctl:target2 at /usr/share/perl5/PVE/Storage/LunCmd/FreeNAS.pm line 124.
> Jul  9 10:04:32 prox01test pvedaemon[94112]: <root@pam> end task UPID:prox01test:00016FCB:016C7286:5B42A68F:qmcreate:112:root@pam: create failed - error with cfs lock 'storage-zfs-over-scsi0': Unable to find the target id for iqn.2005-10.org.freenas.ctl:target2 at /usr/share/perl5/PVE/Storage/LunCmd/FreeNAS.pm line 124.

Entries on the FreeNAS side in `/var/log/debug.log`:

> Jul  9 10:04:32 freenas uwsgi: [api.utils:12] Traceback (most recent call last):
> Jul  9 10:04:32 freenas uwsgi: [api.utils:12]   File "./freenasUI/api/utils.py", line 247, in dispatch
> Jul  9 10:04:32 freenas uwsgi: [api.utils:12]     request_type, request, *args, **kwargs
> Jul  9 10:04:32 freenas uwsgi: [api.utils:12]   File "/usr/local/lib/python3.6/site-packages/tastypie/resources.py", line 477, in dispatch
> Jul  9 10:04:32 freenas uwsgi: [api.utils:12]     self.is_authenticated(request)
> Jul  9 10:04:32 freenas uwsgi: [api.utils:12]   File "/usr/local/lib/python3.6/site-packages/tastypie/resources.py", line 563, in is_authenticated
> Jul  9 10:04:32 freenas uwsgi: [api.utils:12]     raise ImmediateHttpResponse(response=auth_result)
> Jul  9 10:04:32 freenas uwsgi: [api.utils:12] tastypie.exceptions.ImmediateHttpResponse
> Jul  9 10:04:32 freenas uwsgi: [api.utils:12] Traceback (most recent call last):
> Jul  9 10:04:32 freenas uwsgi: [api.utils:12]   File "./freenasUI/api/utils.py", line 247, in dispatch
> Jul  9 10:04:32 freenas uwsgi: [api.utils:12]     request_type, request, *args, **kwargs
> Jul  9 10:04:32 freenas uwsgi: [api.utils:12]   File "/usr/local/lib/python3.6/site-packages/tastypie/resources.py", line 477, in dispatch
> Jul  9 10:04:32 freenas uwsgi: [api.utils:12]     self.is_authenticated(request)
> Jul  9 10:04:32 freenas uwsgi: [api.utils:12]   File "/usr/local/lib/python3.6/site-packages/tastypie/resources.py", line 563, in is_authenticated
> Jul  9 10:04:32 freenas uwsgi: [api.utils:12]     raise ImmediateHttpResponse(response=auth_result)
> Jul  9 10:04:32 freenas uwsgi: [api.utils:12] tastypie.exceptions.ImmediateHttpResponse
> Jul  9 10:04:32 freenas uwsgi: [api.utils:12] Traceback (most recent call last):
> Jul  9 10:04:32 freenas uwsgi: [api.utils:12]   File "./freenasUI/api/utils.py", line 247, in dispatch
> Jul  9 10:04:32 freenas uwsgi: [api.utils:12]     request_type, request, *args, **kwargs
> Jul  9 10:04:32 freenas uwsgi: [api.utils:12]   File "/usr/local/lib/python3.6/site-packages/tastypie/resources.py", line 477, in dispatch
> Jul  9 10:04:32 freenas uwsgi: [api.utils:12]     self.is_authenticated(request)
> Jul  9 10:04:32 freenas uwsgi: [api.utils:12]   File "/usr/local/lib/python3.6/site-packages/tastypie/resources.py", line 563, in is_authenticated
> Jul  9 10:04:32 freenas uwsgi: [api.utils:12]     raise ImmediateHttpResponse(response=auth_result)
> Jul  9 10:04:32 freenas uwsgi: [api.utils:12] tastypie.exceptions.ImmediateHttpResponse
> Jul  9 10:04:32 freenas uwsgi: [api.utils:12] Traceback (most recent call last):
> Jul  9 10:04:32 freenas uwsgi: [api.utils:12]   File "./freenasUI/api/utils.py", line 247, in dispatch
> Jul  9 10:04:32 freenas uwsgi: [api.utils:12]     request_type, request, *args, **kwargs
> Jul  9 10:04:32 freenas uwsgi: [api.utils:12]   File "/usr/local/lib/python3.6/site-packages/tastypie/resources.py", line 477, in dispatch
> Jul  9 10:04:32 freenas uwsgi: [api.utils:12]     self.is_authenticated(request)
> Jul  9 10:04:32 freenas uwsgi: [api.utils:12]   File "/usr/local/lib/python3.6/site-packages/tastypie/resources.py", line 563, in is_authenticated
> Jul  9 10:04:32 freenas uwsgi: [api.utils:12]     raise ImmediateHttpResponse(response=auth_result)
> Jul  9 10:04:32 freenas uwsgi: [api.utils:12] tastypie.exceptions.ImmediateHttpResponse
> Jul  9 10:04:32 freenas uwsgi: [api.utils:12] Traceback (most recent call last):
> Jul  9 10:04:32 freenas uwsgi: [api.utils:12]   File "./freenasUI/api/utils.py", line 247, in dispatch
> Jul  9 10:04:32 freenas uwsgi: [api.utils:12]     request_type, request, *args, **kwargs
> Jul  9 10:04:32 freenas uwsgi: [api.utils:12]   File "/usr/local/lib/python3.6/site-packages/tastypie/resources.py", line 477, in dispatch
> Jul  9 10:04:32 freenas uwsgi: [api.utils:12]     self.is_authenticated(request)
> Jul  9 10:04:32 freenas uwsgi: [api.utils:12]   File "/usr/local/lib/python3.6/site-packages/tastypie/resources.py", line 563, in is_authenticated
> Jul  9 10:04:32 freenas uwsgi: [api.utils:12]     raise ImmediateHttpResponse(response=auth_result)
> Jul  9 10:04:32 freenas uwsgi: [api.utils:12] tastypie.exceptions.ImmediateHttpResponse
> Jul  9 10:04:32 freenas uwsgi: [api.utils:12] Traceback (most recent call last):
> Jul  9 10:04:32 freenas uwsgi: [api.utils:12]   File "./freenasUI/api/utils.py", line 247, in dispatch
> Jul  9 10:04:32 freenas uwsgi: [api.utils:12]     request_type, request, *args, **kwargs
> Jul  9 10:04:32 freenas uwsgi: [api.utils:12]   File "/usr/local/lib/python3.6/site-packages/tastypie/resources.py", line 477, in dispatch
> Jul  9 10:04:32 freenas uwsgi: [api.utils:12]     self.is_authenticated(request)
> Jul  9 10:04:32 freenas uwsgi: [api.utils:12]   File "/usr/local/lib/python3.6/site-packages/tastypie/resources.py", line 563, in is_authenticated
> Jul  9 10:04:32 freenas uwsgi: [api.utils:12]     raise ImmediateHttpResponse(response=auth_result)
> Jul  9 10:04:32 freenas uwsgi: [api.utils:12] tastypie.exceptions.ImmediateHttpResponse
> Jul  9 10:04:32 freenas uwsgi: [api.utils:12] Traceback (most recent call last):
> Jul  9 10:04:32 freenas uwsgi: [api.utils:12]   File "./freenasUI/api/utils.py", line 247, in dispatch
> Jul  9 10:04:32 freenas uwsgi: [api.utils:12]     request_type, request, *args, **kwargs
> Jul  9 10:04:32 freenas uwsgi: [api.utils:12]   File "/usr/local/lib/python3.6/site-packages/tastypie/resources.py", line 477, in dispatch
> Jul  9 10:04:32 freenas uwsgi: [api.utils:12]     self.is_authenticated(request)
> Jul  9 10:04:32 freenas uwsgi: [api.utils:12]   File "/usr/local/lib/python3.6/site-packages/tastypie/resources.py", line 563, in is_authenticated
> Jul  9 10:04:32 freenas uwsgi: [api.utils:12]     raise ImmediateHttpResponse(response=auth_result)
> Jul  9 10:04:32 freenas uwsgi: [api.utils:12] tastypie.exceptions.ImmediateHttpResponse
> Jul  9 10:04:32 freenas uwsgi: [api.utils:12] Traceback (most recent call last):
> Jul  9 10:04:32 freenas uwsgi: [api.utils:12]   File "./freenasUI/api/utils.py", line 247, in dispatch
> Jul  9 10:04:32 freenas uwsgi: [api.utils:12]     request_type, request, *args, **kwargs
> Jul  9 10:04:32 freenas uwsgi: [api.utils:12]   File "/usr/local/lib/python3.6/site-packages/tastypie/resources.py", line 477, in dispatch
> Jul  9 10:04:32 freenas uwsgi: [api.utils:12]     self.is_authenticated(request)
> Jul  9 10:04:32 freenas uwsgi: [api.utils:12]   File "/usr/local/lib/python3.6/site-packages/tastypie/resources.py", line 563, in is_authenticated
> Jul  9 10:04:32 freenas uwsgi: [api.utils:12]     raise ImmediateHttpResponse(response=auth_result)
> Jul  9 10:04:32 freenas uwsgi: [api.utils:12] tastypie.exceptions.ImmediateHttpResponse

**Comment by jrdeck** [comment]
I have done a packet capture from the Proxmox box. For each HTTP request, I can indeed see FreeNAS returning a 401, with the notation `[Malformed Packet: Line-based text data]`

![image](https://user-images.githubusercontent.com/12653888/42425761-9ef13e00-8364-11e8-9b4f-389872ec18ea.png)

If I replicate the GET request from my desktop, it works correctly:

![image](https://user-images.githubusercontent.com/12653888/42425775-cdea5a2a-8364-11e8-881c-ddc510ed8b68.png)

**Comment by jrdeck** [comment]
Whoops - it was the wrong password in the web UI...!
